### ISSUE TITLE
Duplicate records in the output of FullPointsOfUnitalRepresentatives

### ISSUE THREAD

**Issue by davidmezofi** [nagygp/UnitalSZ#15]
Somehow the function `FullPointsOfUnitalRepresentatives` produces some interesting results. E.g.
```
Filtered( Collected( FullPointsOfUnitalRepresentatives( KrcadinacAbstractUnital( 1246 ) ) ),
           x -> x[2] > 1 );
```
is not an empty list, meaning, there are records in the output of `FullPointsOfUnitalRepresentatives` such that the fields `block1`, `block2` and `fullpts` are the same. Since the full points in this function are computed for pairs of blocks up to automorphism, I think there shouldn't be identical pairs of blocks in the output.

**Comment by nagygp** [comment]
@davidmezofi, please have a look at the branch issue_duplicate_records. I hope this fixes the problem.

**Comment by davidmezofi** [comment]
@nagygp, it looks good to me. I tested it on the Krcadinac unitals, works fine. Let's open a pull request, and then I think this issue is solved.

**Comment by nagygp** [comment]
I merged and deleted the branch.
